// AWS Dimensions
// This file is auto-merged into the full dimensionList by dimensions/index.ts
import { DimensionCategory } from '../metric_types';
import { dims } from './helpers';

export const dimensions = dims(DimensionCategory.AWS, [
  // ── Source ──
  ['Source AWS Account', 'kt_aws_src_acc_id'],
  ['Source AWS Account Alias', 'kt_aws_src_acc_alias'],
  ['Source AWS Account Name', 'kt_aws_src_acc_name'],
  ['Source AWS Instance Name', 'kt_aws_src_vm_name'],
  ['Source AWS Instance', 'kt_aws_src_vm_id'],
  ['Source AWS Region', 'kt_aws_src_region'],
  ['Source AWS Zone Name', 'kt_aws_src_zone'],
  ['Source AWS Zone ID', 'kt_aws_src_zone_id'],
  ['Source AWS Instance Type', 'kt_aws_src_vm_type'],
  ['Source AWS Image ID', 'kt_aws_src_image_id'],
  ['Source AWS Security Group', 'kt_aws_src_sg'],
  ['Source AWS Auto Scaling Group', 'kt_aws_src_asg'],
  ['Source AWS Public DNS Name', 'kt_aws_src_pub_dns'],
  ['Source AWS Private DNS Name', 'kt_aws_src_priv_dns'],
  ['Source AWS VPC ID', 'kt_aws_src_vpc_id'],
  ['Source AWS VPC Name', 'kt_aws_src_vpc_name'],
  ['Source AWS Subnet ID', 'kt_aws_src_subnet_id'],
  ['Source AWS Subnet Name', 'kt_aws_src_subnet_name'],
  ['Source AWS Instance Tags', 'kt_aws_src_vm_tags'],
  ['Source AWS Packet Address', 'ktsubtype__aws_subnet__INET_00'],
  ['Source AWS Interface ID', 'ktsubtype__aws_subnet__STR20'],
  ['Source AWS Interface Type', 'ktsubtype__aws_subnet__INT02'],
  ['Source AWS Service', 'ktsubtype__aws_subnet__INT04'],
  ['Source AWS ENI Description', 'ktsubtype__aws_subnet__STR21'],
  ['Source AWS ENI Entity Name', 'ktsubtype__aws_subnet__STR23'],
  ['Source AWS ENI Entity Type', 'ktsubtype__aws_subnet__INT08'],
  ['Source AWS TGW AZ ID', 'ktsubtype__aws_subnet__STR35'],
  ['Source AWS TGW ENI', 'ktsubtype__aws_subnet__STR36'],
  ['Source AWS TGW Subnet ID', 'ktsubtype__aws_subnet__STR37'],
  ['Source AWS TGW VPC ID', 'ktsubtype__aws_subnet__STR38'],
  ['Source AWS TGW VPC Account ID', 'ktsubtype__aws_subnet__INT64_06'],
  ['Source Core Network Edge Location', 'ktsubtype__aws_subnet__STR39'],
  ['Source Core Network Edge Attachment ID', 'ktsubtype__aws_subnet__STR41'],
  ['Source Core Network Edge Attachment ENI', 'ktsubtype__aws_subnet__STR43'],
  ['Source Packet Address VPC ID', 'ktsubtype__aws_subnet__STR53'],

  // ── Destination ──
  ['Destination AWS Account', 'kt_aws_dst_acc_id'],
  ['Destination AWS Account Alias', 'kt_aws_dst_acc_alias'],
  ['Destination AWS Account Name', 'kt_aws_dst_acc_name'],
  ['Destination AWS Instance Name', 'kt_aws_dst_vm_name'],
  ['Destination AWS Instance', 'kt_aws_dst_vm_id'],
  ['Destination AWS Region', 'kt_aws_dst_region'],
  ['Destination AWS Zone Name', 'kt_aws_dst_zone'],
  ['Destination AWS Zone ID', 'kt_aws_dst_zone_id'],
  ['Destination AWS Instance Type', 'kt_aws_dst_vm_type'],
  ['Destination AWS Image ID', 'kt_aws_dst_image_id'],
  ['Destination AWS Security Group', 'kt_aws_dst_sg'],
  ['Destination AWS Auto Scaling Group', 'kt_aws_dst_asg'],
  ['Destination AWS Public DNS Name', 'kt_aws_dst_pub_dns'],
  ['Destination AWS Private DNS Name', 'kt_aws_dst_priv_dns'],
  ['Destination AWS VPC ID', 'kt_aws_dst_vpc_id'],
  ['Destination AWS VPC Name', 'kt_aws_dst_vpc_name'],
  ['Destination AWS Subnet ID', 'kt_aws_dst_subnet_id'],
  ['Destination AWS Subnet Name', 'kt_aws_dst_subnet_name'],
  ['Destination AWS Instance Tags', 'kt_aws_dst_vm_tags'],
  ['Destination AWS Packet Address', 'ktsubtype__aws_subnet__INET_01'],
  ['Destination AWS Gateway ID', 'ktsubtype__aws_subnet__STR17'],
  ['Destination AWS Gateway Type', 'ktsubtype__aws_subnet__STR19'],
  ['Destination AWS Forwarding State', 'ktsubtype__aws_subnet__STR04'],
  ['Destination AWS Interface ID', 'ktsubtype__aws_subnet__STR09'],
  ['Destination AWS Interface Type', 'ktsubtype__aws_subnet__INT03'],
  ['Destination AWS Service', 'ktsubtype__aws_subnet__INT05'],
  ['Destination AWS ENI Description', 'ktsubtype__aws_subnet__STR22'],
  ['Destination AWS ENI Entity Name', 'ktsubtype__aws_subnet__STR24'],
  ['Destination AWS ENI Entity Type', 'ktsubtype__aws_subnet__INT09'],
  ['Destination AWS TGW AZ ID', 'ktsubtype__aws_subnet__STR29'],
  ['Destination AWS TGW ENI', 'ktsubtype__aws_subnet__STR30'],
  ['Destination AWS TGW Subnet ID', 'ktsubtype__aws_subnet__STR31'],
  ['Destination AWS TGW VPC ID', 'ktsubtype__aws_subnet__STR32'],
  ['Destination AWS TGW VPC Account ID', 'ktsubtype__aws_subnet__INT64_05'],
  ['Destination Core Network Edge Location', 'ktsubtype__aws_subnet__STR40'],
  ['Destination Core Network Edge Attachment ID', 'ktsubtype__aws_subnet__STR42'],
  ['Destination Core Network Edge Attachment ENI', 'ktsubtype__aws_subnet__STR44'],
  ['Destination Packet Address VPC ID', 'ktsubtype__aws_subnet__STR54'],

  // ── Common / Non-directional ──
  ['AWS Firewall Action', 'kt_aws_action'],
  ['AWS Logging Status', 'kt_aws_status'],
  ['AWS Start Time', 'ktsubtype__aws_subnet__INT00'],
  ['AWS End Time', 'ktsubtype__aws_subnet__INT01'],
  ['AWS Observing Interface ID', 'ktsubtype__aws_subnet__STR03'],
  ['AWS Flow Log Account ID', 'ktsubtype__aws_subnet__INT64_00'],
  ['AWS Flow Direction', 'ktsubtype__aws_subnet__INT06'],
  ['AWS Traffic Path', 'ktsubtype__aws_subnet__INT07'],
  ['AWS Cloud Ultimate Exit', 'ktsubtype__aws_subnet__STR25'],
  ['AWS Cloud Ultimate Exit Type', 'ktsubtype__aws_subnet__STR26'],
  ['AWS Observing VPC ID', 'ktsubtype__aws_subnet__STR10'],
  ['AWS Observing Subnet ID', 'ktsubtype__aws_subnet__STR11'],
  ['AWS Observing Instance ID', 'ktsubtype__aws_subnet__STR12'],
  ['AWS Observing Region', 'ktsubtype__aws_subnet__STR14'],
  ['AWS Observing Availability Zone ID', 'ktsubtype__aws_subnet__STR15'],
  ['AWS Observing Sublocation ID', 'ktsubtype__aws_subnet__STR16'],
  ['AWS Resource Type', 'ktsubtype__aws_subnet__STR27'],
  ['AWS TGW Attachment ID', 'ktsubtype__aws_subnet__STR28'],
  ['AWS TGW ID', 'ktsubtype__aws_subnet__STR33'],
  ['AWS TGW Pair Attachment ID', 'ktsubtype__aws_subnet__STR34'],
  ['AWS Packets Lost - Blackhole', 'ktsubtype__aws_subnet__INT64_01'],
  ['AWS Packets Lost - MTU Exceeded', 'ktsubtype__aws_subnet__INT64_02'],
  ['AWS Packets Lost - No Route', 'ktsubtype__aws_subnet__INT64_03'],
  ['AWS Packets Lost - TTL Expired', 'ktsubtype__aws_subnet__INT64_04'],
  ['Core Network ID', 'ktsubtype__aws_subnet__STR45'],
  ['Core Network Segment', 'ktsubtype__aws_subnet__STR46'],
  ['Global Network ID', 'ktsubtype__aws_subnet__STR47'],
  ['Firewall Name', 'ktsubtype__aws_subnet__STR48'],
  ['Firewall ARN', 'ktsubtype__aws_subnet__STR49'],
  ['Firewall Policy Name', 'ktsubtype__aws_subnet__STR50'],
  ['Firewall Policy ARN', 'ktsubtype__aws_subnet__STR51'],
  ['Firewall Signature ID', 'ktsubtype__aws_subnet__STR52'],
  ['Firewall Signature Name', 'ktsubtype__aws_subnet__STR55'],
  ['Firewall Alert Category', 'ktsubtype__aws_subnet__STR56'],
  ['Firewall Alert Severity', 'ktsubtype__aws_subnet__STR57'],
  ['Firewall TLS SNI', 'ktsubtype__aws_subnet__STR58'],
  ['Firewall TLS Version', 'ktsubtype__aws_subnet__STR59'],
]);
