// Oracle Cloud (OCI) Dimensions
// This file is auto-merged into the full dimensionList by dimensions/index.ts
import { Dimension, DimensionCategory } from '../metric_types';

export const dimensions: Dimension[] = [
  { text: 'Source OCI Subnet Name', value: 'ktsubtype__oci_subnet__STR06', field: 'ktsubtype__oci_subnet__STR06', category: DimensionCategory.OCI },
  { text: 'Source OCI VCN Name', value: 'ktsubtype__oci_subnet__STR08', field: 'ktsubtype__oci_subnet__STR08', category: DimensionCategory.OCI },
  { text: 'Source OCI Region', value: 'ktsubtype__oci_subnet__STR10', field: 'ktsubtype__oci_subnet__STR10', category: DimensionCategory.OCI },
  { text: 'Source OCI VNIC Name', value: 'ktsubtype__oci_subnet__STR12', field: 'ktsubtype__oci_subnet__STR12', category: DimensionCategory.OCI },
  { text: 'Source OCI Instance Name', value: 'ktsubtype__oci_subnet__STR14', field: 'ktsubtype__oci_subnet__STR14', category: DimensionCategory.OCI },
  { text: 'Source OCI Dynamic Routing Gateway Name', value: 'ktsubtype__oci_subnet__STR16', field: 'ktsubtype__oci_subnet__STR16', category: DimensionCategory.OCI },
  { text: 'Source OCI Local Peering Gateway Name', value: 'ktsubtype__oci_subnet__STR18', field: 'ktsubtype__oci_subnet__STR18', category: DimensionCategory.OCI },
  { text: 'Source OCI Availability Domain', value: 'ktsubtype__oci_subnet__STR25', field: 'ktsubtype__oci_subnet__STR25', category: DimensionCategory.OCI },
  { text: 'Source OCI Instance OCID', value: 'ktsubtype__oci_subnet__STR27', field: 'ktsubtype__oci_subnet__STR27', category: DimensionCategory.OCI },
  { text: 'Source OCI VNIC OCID', value: 'ktsubtype__oci_subnet__STR29', field: 'ktsubtype__oci_subnet__STR29', category: DimensionCategory.OCI },
  { text: 'Source OCI Subnet OCID', value: 'ktsubtype__oci_subnet__STR31', field: 'ktsubtype__oci_subnet__STR31', category: DimensionCategory.OCI },
  { text: 'Source OCI Compartment OCID', value: 'ktsubtype__oci_subnet__STR33', field: 'ktsubtype__oci_subnet__STR33', category: DimensionCategory.OCI },
  { text: 'Source OCI VCN OCID', value: 'ktsubtype__oci_subnet__STR35', field: 'ktsubtype__oci_subnet__STR35', category: DimensionCategory.OCI },
  { text: 'Destination OCI Subnet Name', value: 'ktsubtype__oci_subnet__STR07', field: 'ktsubtype__oci_subnet__STR07', category: DimensionCategory.OCI },
  { text: 'Destination OCI VCN Name', value: 'ktsubtype__oci_subnet__STR09', field: 'ktsubtype__oci_subnet__STR09', category: DimensionCategory.OCI },
  { text: 'Destination OCI Region', value: 'ktsubtype__oci_subnet__STR11', field: 'ktsubtype__oci_subnet__STR11', category: DimensionCategory.OCI },
  { text: 'Destination OCI VNIC Name', value: 'ktsubtype__oci_subnet__STR13', field: 'ktsubtype__oci_subnet__STR13', category: DimensionCategory.OCI },
  { text: 'Destination OCI Instance Name', value: 'ktsubtype__oci_subnet__STR15', field: 'ktsubtype__oci_subnet__STR15', category: DimensionCategory.OCI },
  { text: 'Destination OCI Dynamic Routing Gateway Name', value: 'ktsubtype__oci_subnet__STR17', field: 'ktsubtype__oci_subnet__STR17', category: DimensionCategory.OCI },
  { text: 'Destination OCI Local Peering Gateway Name', value: 'ktsubtype__oci_subnet__STR19', field: 'ktsubtype__oci_subnet__STR19', category: DimensionCategory.OCI },
  { text: 'Destination OCI Availability Domain', value: 'ktsubtype__oci_subnet__STR26', field: 'ktsubtype__oci_subnet__STR26', category: DimensionCategory.OCI },
  { text: 'Destination OCI Instance OCID', value: 'ktsubtype__oci_subnet__STR28', field: 'ktsubtype__oci_subnet__STR28', category: DimensionCategory.OCI },
  { text: 'Destination OCI VNIC OCID', value: 'ktsubtype__oci_subnet__STR30', field: 'ktsubtype__oci_subnet__STR30', category: DimensionCategory.OCI },
  { text: 'Destination OCI Subnet OCID', value: 'ktsubtype__oci_subnet__STR32', field: 'ktsubtype__oci_subnet__STR32', category: DimensionCategory.OCI },
  { text: 'Destination OCI Compartment OCID', value: 'ktsubtype__oci_subnet__STR34', field: 'ktsubtype__oci_subnet__STR34', category: DimensionCategory.OCI },
  { text: 'Destination OCI VCN OCID', value: 'ktsubtype__oci_subnet__STR36', field: 'ktsubtype__oci_subnet__STR36', category: DimensionCategory.OCI },
  { text: 'OCI Action', value: 'ktsubtype__oci_subnet__STR00', field: 'ktsubtype__oci_subnet__STR00', category: DimensionCategory.OCI },
  { text: 'OCI Status', value: 'ktsubtype__oci_subnet__STR01', field: 'ktsubtype__oci_subnet__STR01', category: DimensionCategory.OCI },
  { text: 'OCI Tenant OCID', value: 'ktsubtype__oci_subnet__STR02', field: 'ktsubtype__oci_subnet__STR02', category: DimensionCategory.OCI },
  { text: 'OCI VNIC OCID', value: 'ktsubtype__oci_subnet__STR03', field: 'ktsubtype__oci_subnet__STR03', category: DimensionCategory.OCI },
  { text: 'OCI VNIC Compartment OCID', value: 'ktsubtype__oci_subnet__STR04', field: 'ktsubtype__oci_subnet__STR04', category: DimensionCategory.OCI },
  { text: 'OCI VNIC Subnet OCID', value: 'ktsubtype__oci_subnet__STR05', field: 'ktsubtype__oci_subnet__STR05', category: DimensionCategory.OCI },
  { text: 'OCI Internet Gateway', value: 'ktsubtype__oci_subnet__STR20', field: 'ktsubtype__oci_subnet__STR20', category: DimensionCategory.OCI },
  { text: 'OCI NAT Gateway', value: 'ktsubtype__oci_subnet__STR21', field: 'ktsubtype__oci_subnet__STR21', category: DimensionCategory.OCI },
  { text: 'OCI Service Gateway', value: 'ktsubtype__oci_subnet__STR22', field: 'ktsubtype__oci_subnet__STR22', category: DimensionCategory.OCI },
  { text: 'OCI IPsec Connection Name', value: 'ktsubtype__oci_subnet__STR23', field: 'ktsubtype__oci_subnet__STR23', category: DimensionCategory.OCI },
  { text: 'OCI Virtual Circuit Name', value: 'ktsubtype__oci_subnet__STR24', field: 'ktsubtype__oci_subnet__STR24', category: DimensionCategory.OCI },
  { text: 'OCI Start Time', value: 'ktsubtype__oci_subnet__INT00', field: 'ktsubtype__oci_subnet__INT00', category: DimensionCategory.OCI },
  { text: 'OCI End Time', value: 'ktsubtype__oci_subnet__INT01', field: 'ktsubtype__oci_subnet__INT01', category: DimensionCategory.OCI },
  { text: 'OCI Ingest Time Delta', value: 'ktsubtype__oci_subnet__INT02', field: 'ktsubtype__oci_subnet__INT02', category: DimensionCategory.OCI },
];
