// SNMP & Streaming Telemetry Dimensions
// This file is auto-merged into the full dimensionList by dimensions/index.ts
import { Dimension, DimensionClass, DimensionCategory } from '../metric_types';

export const dimensions: Dimension[] = [
  {
    text: 'SNMP Device Error',
    value: 'ktappprotocol__snmp_device_metrics__STR00',
    field: 'ktappprotocol__snmp_device_metrics__STR00',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Device Component',
    value: 'ktappprotocol__snmp_device_metrics__STR01',
    field: 'ktappprotocol__snmp_device_metrics__STR01',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Device Uptime',
    value: 'ktappprotocol__snmp_device_metrics__INT64_05',
    field: 'ktappprotocol__snmp_device_metrics__INT64_05',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Device',
    value: 'ktappprotocol__snmp_device_metrics__i_device_name',
    field: 'ktappprotocol__snmp_device_metrics__i_device_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Device Site',
    value: 'ktappprotocol__snmp_device_metrics__i_device_site_name',
    field: 'ktappprotocol__snmp_device_metrics__i_device_site_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Cisco RAS Monitorings Device Name',
    value: 'ktappprotocol__ktranslate_cisco_ras__i_device_name',
    field: 'ktappprotocol__ktranslate_cisco_ras__i_device_name',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Dataset',
    value: 'ktappprotocol__event_snmp_traps__STR00',
    field: 'ktappprotocol__event_snmp_traps__STR00',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Trap Type',
    value: 'ktappprotocol__event_snmp_traps__INT00',
    field: 'ktappprotocol__event_snmp_traps__INT00',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Uptime',
    value: 'ktappprotocol__event_snmp_traps__INT64_00',
    field: 'ktappprotocol__event_snmp_traps__INT64_00',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Event ID',
    value: 'ktappprotocol__event_snmp_traps__STR01',
    field: 'ktappprotocol__event_snmp_traps__STR01',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Timestamp',
    value: 'ktappprotocol__event_snmp_traps__INT64_01',
    field: 'ktappprotocol__event_snmp_traps__INT64_01',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Event Type',
    value: 'ktappprotocol__event_snmp_traps__INT06',
    field: 'ktappprotocol__event_snmp_traps__INT06',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Device',
    value: 'ktappprotocol__event_snmp_traps__i_device_name',
    field: 'ktappprotocol__event_snmp_traps__i_device_name',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Trap OID',
    value: 'ktappprotocol__event_snmp_traps__STR02',
    field: 'ktappprotocol__event_snmp_traps__STR02',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Raw PDUs',
    value: 'ktappprotocol__event_snmp_traps__STR03',
    field: 'ktappprotocol__event_snmp_traps__STR03',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Parsed KVs',
    value: 'ktappprotocol__event_snmp_traps__STR24',
    field: 'ktappprotocol__event_snmp_traps__STR24',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Agent',
    value: 'ktappprotocol__event_snmp_traps__kagent_id',
    field: 'ktappprotocol__event_snmp_traps__kagent_id',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Parsed PDUs',
    value: 'ktappprotocol__event_snmp_traps__STR58',
    field: 'ktappprotocol__event_snmp_traps__STR58',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Serial Number',
    value: 'ktappprotocol__event_snmp_traps__STR04',
    field: 'ktappprotocol__event_snmp_traps__STR04',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps System Name',
    value: 'ktappprotocol__event_snmp_traps__STR05',
    field: 'ktappprotocol__event_snmp_traps__STR05',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Admin Status',
    value: 'ktappprotocol__event_snmp_traps__INT01',
    field: 'ktappprotocol__event_snmp_traps__INT01',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Interface',
    value: 'ktappprotocol__event_snmp_traps__input_port',
    field: 'ktappprotocol__event_snmp_traps__input_port',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Interface IP Address',
    value: 'ktappprotocol__event_snmp_traps__INET_00',
    field: 'ktappprotocol__event_snmp_traps__INET_00',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Interface IPv6 Address',
    value: 'ktappprotocol__event_snmp_traps__STR06',
    field: 'ktappprotocol__event_snmp_traps__STR06',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Interface Name',
    value: 'ktappprotocol__event_snmp_traps__STR07',
    field: 'ktappprotocol__event_snmp_traps__STR07',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Interface Netmask',
    value: 'ktappprotocol__event_snmp_traps__INET_01',
    field: 'ktappprotocol__event_snmp_traps__INET_01',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Oper Status',
    value: 'ktappprotocol__event_snmp_traps__INT02',
    field: 'ktappprotocol__event_snmp_traps__INT02',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Status Change Reason',
    value: 'ktappprotocol__event_snmp_traps__STR08',
    field: 'ktappprotocol__event_snmp_traps__STR08',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Bytes In',
    value: 'ktappprotocol__event_snmp_traps__in_bytes',
    field: 'ktappprotocol__event_snmp_traps__in_bytes',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Packets In',
    value: 'ktappprotocol__event_snmp_traps__in_pkts',
    field: 'ktappprotocol__event_snmp_traps__in_pkts',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Destination Port',
    value: 'ktappprotocol__event_snmp_traps__l4_dst_port',
    field: 'ktappprotocol__event_snmp_traps__l4_dst_port',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Source Port',
    value: 'ktappprotocol__event_snmp_traps__l4_src_port',
    field: 'ktappprotocol__event_snmp_traps__l4_src_port',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Protocol',
    value: 'ktappprotocol__event_snmp_traps__INT03',
    field: 'ktappprotocol__event_snmp_traps__INT03',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Protocol',
    value: 'ktappprotocol__event_snmp_traps__i_protocol_name',
    field: 'ktappprotocol__event_snmp_traps__i_protocol_name',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps BGP Peer',
    value: 'ktappprotocol__event_snmp_traps__INET_02',
    field: 'ktappprotocol__event_snmp_traps__INET_02',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps BGP Peer ASN',
    value: 'ktappprotocol__event_snmp_traps__INT64_02',
    field: 'ktappprotocol__event_snmp_traps__INT64_02',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps BGP Peer Description',
    value: 'ktappprotocol__event_snmp_traps__STR09',
    field: 'ktappprotocol__event_snmp_traps__STR09',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps BGP Peer Last State',
    value: 'ktappprotocol__event_snmp_traps__INT64_03',
    field: 'ktappprotocol__event_snmp_traps__INT64_03',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps BGP Peer State',
    value: 'ktappprotocol__event_snmp_traps__INT04',
    field: 'ktappprotocol__event_snmp_traps__INT04',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Event Subtype',
    value: 'ktappprotocol__event_snmp_traps__STR10',
    field: 'ktappprotocol__event_snmp_traps__STR10',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Event Text',
    value: 'ktappprotocol__event_snmp_traps__STR11',
    field: 'ktappprotocol__event_snmp_traps__STR11',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Event Type',
    value: 'ktappprotocol__event_snmp_traps__STR12',
    field: 'ktappprotocol__event_snmp_traps__STR12',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Event Source',
    value: 'ktappprotocol__event_snmp_traps__STR13',
    field: 'ktappprotocol__event_snmp_traps__STR13',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Traps Alarm Description',
    value: 'ktappprotocol__event_snmp_traps__STR14',
    field: 'ktappprotocol__event_snmp_traps__STR14',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Dataset',
    value: 'ktappprotocol__event_deviceconf__STR00',
    field: 'ktappprotocol__event_deviceconf__STR00',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Revision',
    value: 'ktappprotocol__event_deviceconf__INT64_00',
    field: 'ktappprotocol__event_deviceconf__INT64_00',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Fetch Status',
    value: 'ktappprotocol__event_deviceconf__INT00',
    field: 'ktappprotocol__event_deviceconf__INT00',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Event ID',
    value: 'ktappprotocol__event_deviceconf__STR01',
    field: 'ktappprotocol__event_deviceconf__STR01',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Device',
    value: 'ktappprotocol__event_deviceconf__i_device_name',
    field: 'ktappprotocol__event_deviceconf__i_device_name',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Timestamp',
    value: 'ktappprotocol__event_deviceconf__INT64_01',
    field: 'ktappprotocol__event_deviceconf__INT64_01',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Event Type',
    value: 'ktappprotocol__event_deviceconf__INT01',
    field: 'ktappprotocol__event_deviceconf__INT01',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Agent',
    value: 'ktappprotocol__event_deviceconf__kagent_id',
    field: 'ktappprotocol__event_deviceconf__kagent_id',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Commit Time',
    value: 'ktappprotocol__event_deviceconf__INT64_02',
    field: 'ktappprotocol__event_deviceconf__INT64_02',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Commit User',
    value: 'ktappprotocol__event_deviceconf__STR02',
    field: 'ktappprotocol__event_deviceconf__STR02',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Commit Comment',
    value: 'ktappprotocol__event_deviceconf__STR03',
    field: 'ktappprotocol__event_deviceconf__STR03',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'Device Config Change Commit Method',
    value: 'ktappprotocol__event_deviceconf__STR04',
    field: 'ktappprotocol__event_deviceconf__STR04',
    category: DimensionCategory.SNMP_DEVICE,
  },
  {
    text: 'SNMP Interface',
    value: 'ktappprotocol__snmp__output_port',
    field: 'ktappprotocol__snmp__output_port',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Device',
    value: 'ktappprotocol__snmp__i_device_name',
    field: 'ktappprotocol__snmp__i_device_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Site',
    value: 'ktappprotocol__snmp__i_device_site_name',
    field: 'ktappprotocol__snmp__i_device_site_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Provider',
    value: 'ktappprotocol__snmp__i_dst_provider_classification',
    field: 'ktappprotocol__snmp__i_dst_provider_classification',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Connectivity Type',
    value: 'ktappprotocol__snmp__i_dst_connect_type_name',
    field: 'ktappprotocol__snmp__i_dst_connect_type_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Network Boundary',
    value: 'ktappprotocol__snmp__i_dst_network_bndry_name',
    field: 'ktappprotocol__snmp__i_dst_network_bndry_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Capacity',
    value: 'ktappprotocol__snmp__i_output_interface_speed',
    field: 'ktappprotocol__snmp__i_output_interface_speed',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Admin Status',
    value: 'ktappprotocol__snmp__INT02',
    field: 'ktappprotocol__snmp__INT02',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'SNMP Interface Oper Status',
    value: 'ktappprotocol__snmp__INT03',
    field: 'ktappprotocol__snmp__INT03',
    class: DimensionClass.SNMP,
    category: DimensionCategory.SNMP_INTERFACE,
  },
  {
    text: 'ST Interface',
    value: 'ktappprotocol__st__output_port',
    field: 'ktappprotocol__st__output_port',
    class: DimensionClass.SNMP,
    category: DimensionCategory.ST_INTERFACE,
  },
  {
    text: 'ST Interface Device',
    value: 'ktappprotocol__st__i_device_name',
    field: 'ktappprotocol__st__i_device_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.ST_INTERFACE,
  },
  {
    text: 'ST Interface Site',
    value: 'ktappprotocol__st__i_device_site_name',
    field: 'ktappprotocol__st__i_device_site_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.ST_INTERFACE,
  },
  {
    text: 'ST Interface Provider',
    value: 'ktappprotocol__st__i_dst_provider_classification',
    field: 'ktappprotocol__st__i_dst_provider_classification',
    class: DimensionClass.SNMP,
    category: DimensionCategory.ST_INTERFACE,
  },
  {
    text: 'ST Interface Connectivity Type',
    value: 'ktappprotocol__st__i_dst_connect_type_name',
    field: 'ktappprotocol__st__i_dst_connect_type_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.ST_INTERFACE,
  },
  {
    text: 'ST Interface Network Boundary',
    value: 'ktappprotocol__st__i_dst_network_bndry_name',
    field: 'ktappprotocol__st__i_dst_network_bndry_name',
    class: DimensionClass.SNMP,
    category: DimensionCategory.ST_INTERFACE,
  },
  {
    text: 'ST Interface Capacity',
    value: 'ktappprotocol__st__i_output_interface_speed',
    field: 'ktappprotocol__st__i_output_interface_speed',
    class: DimensionClass.SNMP,
    category: DimensionCategory.ST_INTERFACE,
  },
];
