// Azure Dimensions
// This file is auto-merged into the full dimensionList by dimensions/index.ts
import { DimensionCategory } from '../metric_types';
import { dims } from './helpers';

export const dimensions = dims(DimensionCategory.AZURE, [
  // ── Source ──
  ['Source Azure Instance Name', 'kt_az_src_inst_name'],
  ['Source Azure Instance', 'kt_az_src_inst_id'],
  ['Source Azure Region', 'kt_az_src_region'],
  ['Source Azure Zone', 'kt_az_src_zone'],
  ['Source Azure Instance Type', 'kt_az_src_inst_type'],
  ['Source Azure Public DNS Name', 'kt_az_src_fqdn'],
  ['Source Azure VNet ID', 'kt_az_src_vnet'],
  ['Source Azure Subnet Name', 'kt_az_src_subnet'],
  ['Source Azure Resource Group', 'kt_az_src_rsrc_group'],
  ['Source Azure Public IP Address', 'kt_az_src_public_ip'],
  ['Source Azure Subscription', 'kt_az_src_sub_id'],
  ['Source Azure Subscription Name', 'kt_az_src_sub_name'],
  ['Source Azure Security Rule', 'ktsubtype__azure_subnet__STR01'],
  ['Source Azure Firewall Action', 'ktsubtype__azure_subnet__STR03'],
  ['Source Azure Security Group', 'ktsubtype__azure_subnet__STR05'],
  ['Source Azure Interface Name', 'ktsubtype__azure_subnet__STR06'],
  ['Source Azure Gateway Name', 'ktsubtype__azure_subnet__STR09'],
  ['Source Azure Gateway Type', 'ktsubtype__azure_subnet__STR11'],
  ['Source Azure Load Balancer', 'ktsubtype__azure_subnet__STR23'],

  // ── Destination ──
  ['Destination Azure Instance Name', 'kt_az_dst_inst_name'],
  ['Destination Azure Instance', 'kt_az_dst_inst_id'],
  ['Destination Azure Region', 'kt_az_dst_region'],
  ['Destination Azure Zone', 'kt_az_dst_zone'],
  ['Destination Azure Public DNS Name', 'kt_az_dst_fqdn'],
  ['Destination Azure Instance Type', 'kt_az_dst_inst_type'],
  ['Destination Azure VNet ID', 'kt_az_dst_vnet'],
  ['Destination Azure Subnet Name', 'kt_az_dst_subnet'],
  ['Destination Azure Resource Group', 'kt_az_dst_rsrc_group'],
  ['Destination Azure Public IP Address', 'kt_az_dst_public_ip'],
  ['Destination Azure Subscription', 'kt_az_dst_sub_id'],
  ['Destination Azure Subscription Name', 'kt_az_dst_sub_name'],
  ['Destination Azure Security Rule', 'ktsubtype__azure_subnet__STR00'],
  ['Destination Azure Firewall Action', 'ktsubtype__azure_subnet__STR02'],
  ['Destination Azure Security Group', 'ktsubtype__azure_subnet__STR04'],
  ['Destination Azure Interface Name', 'ktsubtype__azure_subnet__STR07'],
  ['Destination Azure Gateway Name', 'ktsubtype__azure_subnet__STR10'],
  ['Destination Azure Gateway Type', 'ktsubtype__azure_subnet__STR12'],
  ['Destination Azure FQDN', 'ktsubtype__azure_subnet__STR19'],
  ['Destination Azure Load Balancer', 'ktsubtype__azure_subnet__STR24'],

  // ── Common / Non-directional ──
  ['Azure Observing MAC Address', 'ktsubtype__azure_subnet__STR08'],
  ['Azure Ingress Virtual Hub', 'ktsubtype__azure_subnet__STR13'],
  ['Azure Egress Virtual Hub', 'ktsubtype__azure_subnet__STR14'],
  ['Azure ExpressRoute Circuit Name', 'ktsubtype__azure_subnet__STR15'],
  ['Azure ExpressRoute Peering Type', 'ktsubtype__azure_subnet__STR16'],
  ['Azure Firewall Policy', 'ktsubtype__azure_subnet__STR20'],
  ['Azure Firewall Rule', 'ktsubtype__azure_subnet__STR21'],
  ['Azure Application Protocol', 'ktsubtype__azure_subnet__STR22'],
  ['Azure Logging Resource Category', 'ktsubtype__azure_subnet__STR17'],
  ['Azure Logging Resource Name', 'ktsubtype__azure_subnet__STR18'],
  ['Azure Observing Virtual Network Name', 'ktsubtype__azure_subnet__STR27'],
  ['Azure Observing ACL ID', 'ktsubtype__azure_subnet__STR28'],
  ['Azure Observing Security Rule', 'ktsubtype__azure_subnet__STR29'],
  ['Azure Observing Resource Name', 'ktsubtype__azure_subnet__STR30'],
  ['Azure Flow Direction', 'ktsubtype__azure_subnet__INT00'],
  ['Measurement Name', 'ktappprotocol__azure_express_route_metrics__STR00'],
  ['Express Route Circuit Name', 'ktappprotocol__azure_express_route_metrics__STR01'],
  ['Express Route Circuit Peering Name', 'ktappprotocol__azure_express_route_metrics__STR02'],
  ['Measurement Duration', 'ktappprotocol__azure_express_route_metrics__INT00'],
  ['Timestamp', 'ktappprotocol__azure_express_route_metrics__INT64_00'],
]);
