// General Dimensions
// This file is auto-merged into the full dimensionList by dimensions/index.ts
import { Dimension, DimensionClass, DimensionCategory } from '../metric_types';

export const dimensions: Dimension[] = [
  { text: 'Source IP/CIDR', value: 'IP_src', field: 'IP_src', category: DimensionCategory.GENERAL },
  {
    text: 'Source Site by IP',
    value: 'kt_src_site_title',
    field: 'kt_src_site_title',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Source Site Type by IP',
    value: 'kt_src_site_type',
    field: 'kt_src_site_type',
    category: DimensionCategory.GENERAL,
  },
  { text: 'Source Port Number', value: 'Port_src', field: 'Port_src', category: DimensionCategory.GENERAL },
  { text: 'Destination IP/CIDR', value: 'IP_dst', field: 'IP_dst', category: DimensionCategory.GENERAL },
  {
    text: 'Destination Site by IP',
    value: 'kt_dst_site_title',
    field: 'kt_dst_site_title',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Destination Site Type by IP',
    value: 'kt_dst_site_type',
    field: 'kt_dst_site_type',
    category: DimensionCategory.GENERAL,
  },
  { text: 'Destination Port Number', value: 'Port_dst', field: 'Port_dst', category: DimensionCategory.GENERAL },
  { text: 'Protocol', value: 'Proto', field: 'Proto', category: DimensionCategory.GENERAL },
  { text: 'INET Family', value: 'inet_family', field: 'inet_family', category: DimensionCategory.GENERAL },
  { text: 'DSCP', value: 'dscp', field: 'dscp', category: DimensionCategory.GENERAL },
  { text: 'ToS', value: 'TOS', field: 'TOS', category: DimensionCategory.GENERAL },
  {
    text: 'Packet Size',
    value: 'sampledpktsize',
    field: 'sampledpktsize',
    class: DimensionClass.FLOW,
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Packet Size (nearest 100)',
    value: 'sampledpktsize_100',
    field: 'sampledpktsize_100',
    category: DimensionCategory.GENERAL,
  },
  { text: 'Sampling Rate * 100', value: 'sample_rate', field: 'sample_rate', category: DimensionCategory.GENERAL },
  { text: 'IPv6 Flow Label', value: 'ipv6_flow_label', field: 'ipv6_flow_label', category: DimensionCategory.GENERAL },
  { text: 'Application', value: 'application', field: 'application', category: DimensionCategory.GENERAL },
  { text: 'TCP Flags', value: 'tcp_flags', field: 'tcp_flags', category: DimensionCategory.GENERAL },
  {
    text: 'Source Service (Port+Proto)',
    value: 'src_proto_port',
    field: 'src_proto_port',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Source Botnet C&C',
    value: 'src_threat_bnetcc',
    field: 'src_threat_bnetcc',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Source Threat-list Host',
    value: 'src_threat_host',
    field: 'src_threat_host',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Destination Service (Port+Proto)',
    value: 'dst_proto_port',
    field: 'dst_proto_port',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Destination Botnet C&C',
    value: 'dst_threat_bnetcc',
    field: 'dst_threat_bnetcc',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Destination Threat-list Host',
    value: 'dst_threat_host',
    field: 'dst_threat_host',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP OP',
    value: 'ktappprotocol__dhcp__INT00',
    field: 'ktappprotocol__dhcp__INT00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP Message Type',
    value: 'ktappprotocol__dhcp__INT01',
    field: 'ktappprotocol__dhcp__INT01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP CI Address',
    value: 'ktappprotocol__dhcp__INET_00',
    field: 'ktappprotocol__dhcp__INET_00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP YI Address',
    value: 'ktappprotocol__dhcp__INET_01',
    field: 'ktappprotocol__dhcp__INET_01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP SI Address',
    value: 'ktappprotocol__dhcp__INET_02',
    field: 'ktappprotocol__dhcp__INET_02',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP Lease',
    value: 'ktappprotocol__dhcp__INT05',
    field: 'ktappprotocol__dhcp__INT05',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP CH Address',
    value: 'ktappprotocol__dhcp__STR00',
    field: 'ktappprotocol__dhcp__STR00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP Hostname',
    value: 'ktappprotocol__dhcp__STR01',
    field: 'ktappprotocol__dhcp__STR01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'DHCP Domain',
    value: 'ktappprotocol__dhcp__STR02',
    field: 'ktappprotocol__dhcp__STR02',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius Code',
    value: 'ktappprotocol__radius__INT00',
    field: 'ktappprotocol__radius__INT00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius User Name',
    value: 'ktappprotocol__radius__STR00',
    field: 'ktappprotocol__radius__STR00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius Service Type',
    value: 'ktappprotocol__radius__INT01',
    field: 'ktappprotocol__radius__INT01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius Framed IP Address',
    value: 'ktappprotocol__radius__INET_00',
    field: 'ktappprotocol__radius__INET_00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius Framed IP Mask',
    value: 'ktappprotocol__radius__INET_01',
    field: 'ktappprotocol__radius__INET_01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius Framed Protocol',
    value: 'ktappprotocol__radius__STR01',
    field: 'ktappprotocol__radius__STR01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius Accounting Status',
    value: 'ktappprotocol__radius__INT02',
    field: 'ktappprotocol__radius__INT02',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Radius Accounting Session ID',
    value: 'ktappprotocol__radius__STR02',
    field: 'ktappprotocol__radius__STR02',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Dataset',
    value: 'ktappprotocol__event_syslog__STR00',
    field: 'ktappprotocol__event_syslog__STR00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Transport',
    value: 'ktappprotocol__event_syslog__INT00',
    field: 'ktappprotocol__event_syslog__INT00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Format',
    value: 'ktappprotocol__event_syslog__INT01',
    field: 'ktappprotocol__event_syslog__INT01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Framing',
    value: 'ktappprotocol__event_syslog__INT02',
    field: 'ktappprotocol__event_syslog__INT02',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Trailer',
    value: 'ktappprotocol__event_syslog__INT03',
    field: 'ktappprotocol__event_syslog__INT03',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog ParseError',
    value: 'ktappprotocol__event_syslog__STR01',
    field: 'ktappprotocol__event_syslog__STR01',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Priority',
    value: 'ktappprotocol__event_syslog__INT04',
    field: 'ktappprotocol__event_syslog__INT04',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Facility',
    value: 'ktappprotocol__event_syslog__INT05',
    field: 'ktappprotocol__event_syslog__INT05',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Severity',
    value: 'ktappprotocol__event_syslog__INT06',
    field: 'ktappprotocol__event_syslog__INT06',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Hostname',
    value: 'ktappprotocol__event_syslog__STR02',
    field: 'ktappprotocol__event_syslog__STR02',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Application Name',
    value: 'ktappprotocol__event_syslog__STR03',
    field: 'ktappprotocol__event_syslog__STR03',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Process ID',
    value: 'ktappprotocol__event_syslog__STR04',
    field: 'ktappprotocol__event_syslog__STR04',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Message',
    value: 'ktappprotocol__event_syslog__STR05',
    field: 'ktappprotocol__event_syslog__STR05',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Version',
    value: 'ktappprotocol__event_syslog__INT07',
    field: 'ktappprotocol__event_syslog__INT07',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Message ID',
    value: 'ktappprotocol__event_syslog__STR06',
    field: 'ktappprotocol__event_syslog__STR06',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Structured Data (JSON)',
    value: 'ktappprotocol__event_syslog__STR07',
    field: 'ktappprotocol__event_syslog__STR07',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Event ID',
    value: 'ktappprotocol__event_syslog__STR08',
    field: 'ktappprotocol__event_syslog__STR08',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Timestamp',
    value: 'ktappprotocol__event_syslog__INT64_00',
    field: 'ktappprotocol__event_syslog__INT64_00',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Event Type',
    value: 'ktappprotocol__event_syslog__INT08',
    field: 'ktappprotocol__event_syslog__INT08',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Device',
    value: 'ktappprotocol__event_syslog__i_device_name',
    field: 'ktappprotocol__event_syslog__i_device_name',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Raw Log',
    value: 'ktappprotocol__event_syslog__STR09',
    field: 'ktappprotocol__event_syslog__STR09',
    category: DimensionCategory.GENERAL,
  },
  {
    text: 'Syslog Agent',
    value: 'ktappprotocol__event_syslog__kagent_id',
    field: 'ktappprotocol__event_syslog__kagent_id',
    category: DimensionCategory.GENERAL,
  },
];
