// Routing Dimensions
// This file is auto-merged into the full dimensionList by dimensions/index.ts
import { Dimension, DimensionCategory } from '../metric_types';

export const dimensions: Dimension[] = [
  { text: 'Source Route Prefix/LEN', value: 'src_route_prefix_len', field: 'src_route_prefix_len', category: DimensionCategory.ROUTING },
  { text: 'Source Route LEN', value: 'src_route_length', field: 'src_route_length', category: DimensionCategory.ROUTING },
  { text: 'Source AS Number', value: 'AS_src', field: 'AS_src', category: DimensionCategory.ROUTING },
  { text: 'Source AS Number (Generic Table)', value: 'src_asn_generic', field: 'src_asn_generic', category: DimensionCategory.ROUTING },
  { text: 'Source Next Hop IP/CIDR', value: 'src_nexthop_ip', field: 'src_nexthop_ip', category: DimensionCategory.ROUTING },
  { text: 'Source Next Hop AS Number', value: 'src_nexthop_asn', field: 'src_nexthop_asn', category: DimensionCategory.ROUTING },
  { text: 'Source 2nd Hop AS Number', value: 'src_second_asn', field: 'src_second_asn', category: DimensionCategory.ROUTING },
  { text: 'Source 3rd Hop AS Number', value: 'src_third_asn', field: 'src_third_asn', category: DimensionCategory.ROUTING },
  { text: 'Source 2nd Hop AS Number (Collapsed)', value: 'src_secondhop_asn_noprepend', field: 'src_secondhop_asn_noprepend', category: DimensionCategory.ROUTING },
  { text: 'Source 3rd Hop AS Number (Collapsed)', value: 'src_thirdhop_asn_noprepend', field: 'src_thirdhop_asn_noprepend', category: DimensionCategory.ROUTING },
  { text: 'Source AS Path', value: 'src_bgp_aspath', field: 'src_bgp_aspath', category: DimensionCategory.ROUTING },
  { text: 'Source AS Path (Collapsed)', value: 'src_aspath_noprepend', field: 'src_aspath_noprepend', category: DimensionCategory.ROUTING },
  { text: 'Source BGP Community', value: 'src_bgp_community', field: 'src_bgp_community', category: DimensionCategory.ROUTING },
  { text: 'Source BGP Extended Community', value: 'src_bgp_ext_community', field: 'src_bgp_ext_community', category: DimensionCategory.ROUTING },
  { text: 'Source BGP Large Community', value: 'src_bgp_large_community', field: 'src_bgp_large_community', category: DimensionCategory.ROUTING },
  { text: 'Source BGP Origin', value: 'src_bgp_origin', field: 'src_bgp_origin', category: DimensionCategory.ROUTING },
  { text: 'Source VRF Name', value: 'i_input_vrf', field: 'i_input_vrf', category: DimensionCategory.ROUTING },
  { text: 'Source VRF Route Distinguisher', value: 'i_input_vrf_rd', field: 'i_input_vrf_rd', category: DimensionCategory.ROUTING },
  { text: 'Source VRF Route Target', value: 'i_input_vrf_rt', field: 'i_input_vrf_rt', category: DimensionCategory.ROUTING },
  { text: 'Source VRF Extended Route Distinguisher', value: 'input_vrf', field: 'input_vrf', category: DimensionCategory.ROUTING },
  { text: 'Destination Route Prefix/LEN', value: 'dst_route_prefix_len', field: 'dst_route_prefix_len', category: DimensionCategory.ROUTING },
  { text: 'Destination Route LEN', value: 'dst_route_length', field: 'dst_route_length', category: DimensionCategory.ROUTING },
  { text: 'Destination AS Number', value: 'AS_dst', field: 'AS_dst', category: DimensionCategory.ROUTING },
  { text: 'Destination AS Number (Generic Table)', value: 'dst_asn_generic', field: 'dst_asn_generic', category: DimensionCategory.ROUTING },
  { text: 'Destination Next Hop IP/CIDR', value: 'dst_nexthop_ip', field: 'dst_nexthop_ip', category: DimensionCategory.ROUTING },
  { text: 'Destination Next Hop AS Number', value: 'dst_nexthop_asn', field: 'dst_nexthop_asn', category: DimensionCategory.ROUTING },
  { text: 'Destination 2nd Hop AS Number', value: 'dst_second_asn', field: 'dst_second_asn', category: DimensionCategory.ROUTING },
  { text: 'Destination 3rd Hop AS Number', value: 'dst_third_asn', field: 'dst_third_asn', category: DimensionCategory.ROUTING },
  { text: 'Destination 2nd Hop AS Number (Collapsed)', value: 'dst_secondhop_asn_noprepend', field: 'dst_secondhop_asn_noprepend', category: DimensionCategory.ROUTING },
  { text: 'Destination 3rd Hop AS Number (Collapsed)', value: 'dst_thirdhop_asn_noprepend', field: 'dst_thirdhop_asn_noprepend', category: DimensionCategory.ROUTING },
  { text: 'Destination AS Path', value: 'dst_bgp_aspath', field: 'dst_bgp_aspath', category: DimensionCategory.ROUTING },
  { text: 'Destination AS Path (Collapsed)', value: 'dst_aspath_noprepend', field: 'dst_aspath_noprepend', category: DimensionCategory.ROUTING },
  { text: 'Destination BGP Community', value: 'dst_bgp_community', field: 'dst_bgp_community', category: DimensionCategory.ROUTING },
  { text: 'Destination BGP Extended Community', value: 'dst_bgp_ext_community', field: 'dst_bgp_ext_community', category: DimensionCategory.ROUTING },
  { text: 'Destination BGP Large Community', value: 'dst_bgp_large_community', field: 'dst_bgp_large_community', category: DimensionCategory.ROUTING },
  { text: 'Destination BGP Origin', value: 'dst_bgp_origin', field: 'dst_bgp_origin', category: DimensionCategory.ROUTING },
  { text: 'Destination VRF Name', value: 'i_output_vrf', field: 'i_output_vrf', category: DimensionCategory.ROUTING },
  { text: 'Destination VRF Route Distinguisher', value: 'i_output_vrf_rd', field: 'i_output_vrf_rd', category: DimensionCategory.ROUTING },
  { text: 'Destination VRF Route Target', value: 'i_output_vrf_rt', field: 'i_output_vrf_rt', category: DimensionCategory.ROUTING },
  { text: 'Destination VRF Extended Route Distinguisher', value: 'output_vrf', field: 'output_vrf', category: DimensionCategory.ROUTING },
  { text: 'Destination RPKI Validation Status', value: 'i_dst_rpki_name', field: 'i_dst_rpki_name', category: DimensionCategory.ROUTING },
  { text: 'Destination RPKI Quick Status', value: 'i_dst_rpki_min_name', field: 'i_dst_rpki_min_name', category: DimensionCategory.ROUTING },
  { text: 'MPLS Forwarding Type', value: 'ktsubtype__mpls__INT00', field: 'ktsubtype__mpls__INT00', category: DimensionCategory.ROUTING },
  { text: 'MPLS Forwarding Address', value: 'ktsubtype__mpls__INET_00', field: 'ktsubtype__mpls__INET_00', category: DimensionCategory.ROUTING },
  { text: 'MPLS Forwarding Address Prefix Length', value: 'ktsubtype__mpls__INT01', field: 'ktsubtype__mpls__INT01', category: DimensionCategory.ROUTING },
  { text: 'MPLS Label 1', value: 'ktsubtype__mpls__INT03', field: 'ktsubtype__mpls__INT03', category: DimensionCategory.ROUTING },
  { text: 'MPLS Label 1 EXP', value: 'ktsubtype__mpls__INT04', field: 'ktsubtype__mpls__INT04', category: DimensionCategory.ROUTING },
  { text: 'MPLS Label 2', value: 'ktsubtype__mpls__INT05', field: 'ktsubtype__mpls__INT05', category: DimensionCategory.ROUTING },
  { text: 'MPLS Label 2 EXP', value: 'ktsubtype__mpls__INT06', field: 'ktsubtype__mpls__INT06', category: DimensionCategory.ROUTING },
  { text: 'MPLS Forwarding Status', value: 'ktsubtype__mpls__INT02', field: 'ktsubtype__mpls__INT02', category: DimensionCategory.ROUTING },
  { text: 'MPLS Label 3', value: 'ktsubtype__mpls__INT07', field: 'ktsubtype__mpls__INT07', category: DimensionCategory.ROUTING },
  { text: 'MPLS Label 3 EXP', value: 'ktsubtype__mpls__INT08', field: 'ktsubtype__mpls__INT08', category: DimensionCategory.ROUTING },
];
