// Vendor-Specific Dimensions (Palo Alto, Fortinet, Silver Peak, Cisco, VXLAN, etc.)
// This file is auto-merged into the full dimensionList by dimensions/index.ts
import { Dimension, DimensionCategory } from '../metric_types';

export const dimensions: Dimension[] = [
  { text: 'Source Palo Alto Networks Firewall Post-NAT Transport Port', value: 'ktsubtype__paloalto__INT02', field: 'ktsubtype__paloalto__INT02', category: DimensionCategory.PALO_ALTO },
  { text: 'Source Palo Alto Networks Firewall Post-NAT Address', value: 'ktsubtype__paloalto__INET_00', field: 'ktsubtype__paloalto__INET_00', category: DimensionCategory.PALO_ALTO },
  { text: 'Destination Palo Alto Networks Firewall Post-NAT Transport Port', value: 'ktsubtype__paloalto__INT03', field: 'ktsubtype__paloalto__INT03', category: DimensionCategory.PALO_ALTO },
  { text: 'Destination Palo Alto Networks Firewall Post-NAT Address', value: 'ktsubtype__paloalto__INET_01', field: 'ktsubtype__paloalto__INET_01', category: DimensionCategory.PALO_ALTO },
  { text: 'Palo Alto Networks Firewall ICMP Type', value: 'ktsubtype__paloalto__INT00', field: 'ktsubtype__paloalto__INT00', category: DimensionCategory.PALO_ALTO },
  { text: 'Palo Alto Networks Firewall Direction', value: 'ktsubtype__paloalto__INT01', field: 'ktsubtype__paloalto__INT01', category: DimensionCategory.PALO_ALTO },
  { text: 'Palo Alto Networks Firewall Flow ID', value: 'ktsubtype__paloalto__INT64_00', field: 'ktsubtype__paloalto__INT64_00', category: DimensionCategory.PALO_ALTO },
  { text: 'Palo Alto Networks Firewall Firewall Event', value: 'ktsubtype__paloalto__INT04', field: 'ktsubtype__paloalto__INT04', category: DimensionCategory.PALO_ALTO },
  { text: 'Palo Alto Networks Firewall User ID', value: 'ktsubtype__paloalto__STR01', field: 'ktsubtype__paloalto__STR01', category: DimensionCategory.PALO_ALTO },
  { text: 'Palo Alto Networks Firewall Application ID', value: 'ktsubtype__paloalto__STR00', field: 'ktsubtype__paloalto__STR00', category: DimensionCategory.PALO_ALTO },
  { text: 'Cisco NBAR-Enabled Router Application Name', value: 'ktsubtype__cisco_nbar__STR00', field: 'ktsubtype__cisco_nbar__STR00', category: DimensionCategory.CISCO_NVZFLOW },
  { text: 'Cisco NBAR-Enabled Router Application Category', value: 'ktsubtype__cisco_nbar__STR01', field: 'ktsubtype__cisco_nbar__STR01', category: DimensionCategory.CISCO_NVZFLOW },
  { text: 'Cisco NBAR-Enabled Router Application Subcategory', value: 'ktsubtype__cisco_nbar__STR02', field: 'ktsubtype__cisco_nbar__STR02', category: DimensionCategory.CISCO_NVZFLOW },
  { text: 'Cisco NBAR-Enabled Router Application Group', value: 'ktsubtype__cisco_nbar__STR03', field: 'ktsubtype__cisco_nbar__STR03', category: DimensionCategory.CISCO_NVZFLOW },
  { text: 'Cisco NBAR-Enabled Router Application Traffic Class', value: 'ktsubtype__cisco_nbar__STR04', field: 'ktsubtype__cisco_nbar__STR04', category: DimensionCategory.CISCO_NVZFLOW },
  { text: 'Cisco NBAR-Enabled Router Application Business Relevance', value: 'ktsubtype__cisco_nbar__STR05', field: 'ktsubtype__cisco_nbar__STR05', category: DimensionCategory.CISCO_NVZFLOW },
  { text: 'Source Fortinet FortiGate Post-NAT Transport Port', value: 'ktsubtype__fortinet_fortigate__INT02', field: 'ktsubtype__fortinet_fortigate__INT02', category: DimensionCategory.FORTINET },
  { text: 'Source Fortinet FortiGate Post-NAT Address', value: 'ktsubtype__fortinet_fortigate__INET_00', field: 'ktsubtype__fortinet_fortigate__INET_00', category: DimensionCategory.FORTINET },
  { text: 'Destination Fortinet FortiGate Post-NAT Transport Port', value: 'ktsubtype__fortinet_fortigate__INT03', field: 'ktsubtype__fortinet_fortigate__INT03', category: DimensionCategory.FORTINET },
  { text: 'Destination Fortinet FortiGate Post-NAT Address', value: 'ktsubtype__fortinet_fortigate__INET_01', field: 'ktsubtype__fortinet_fortigate__INET_01', category: DimensionCategory.FORTINET },
  { text: 'Fortinet FortiGate Application Name', value: 'ktsubtype__fortinet_fortigate__STR00', field: 'ktsubtype__fortinet_fortigate__STR00', category: DimensionCategory.FORTINET },
  { text: 'Fortinet FortiGate Application Category', value: 'ktsubtype__fortinet_fortigate__STR01', field: 'ktsubtype__fortinet_fortigate__STR01', category: DimensionCategory.FORTINET },
  { text: 'Fortinet FortiGate Flow Flags', value: 'ktsubtype__fortinet_fortigate__INT00', field: 'ktsubtype__fortinet_fortigate__INT00', category: DimensionCategory.FORTINET },
  { text: 'Fortinet FortiGate Forwarding Status', value: 'ktsubtype__fortinet_fortigate__INT01', field: 'ktsubtype__fortinet_fortigate__INT01', category: DimensionCategory.FORTINET },
  { text: 'Fortinet FortiGate Flow end reason', value: 'ktsubtype__fortinet_fortigate__INT04', field: 'ktsubtype__fortinet_fortigate__INT04', category: DimensionCategory.FORTINET },
  { text: 'Cisco SDWAN vEdge Maximum packet length', value: 'ktsubtype__viptela__INT64_00', field: 'ktsubtype__viptela__INT64_00', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SDWAN vEdge Minimum packet length', value: 'ktsubtype__viptela__INT64_01', field: 'ktsubtype__viptela__INT64_01', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SDWAN vEdge VPN identifier', value: 'ktsubtype__viptela__INT64_02', field: 'ktsubtype__viptela__INT64_02', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SDWAN vEdge Flow end reason', value: 'ktsubtype__viptela__INT00', field: 'ktsubtype__viptela__INT00', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SDWAN vEdge Field 4322', value: 'ktsubtype__viptela__INT01', field: 'ktsubtype__viptela__INT01', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Source Cisco SD-WAN IOS XE Overlay Session ID', value: 'ktsubtype__cisco_sdwan_xe__INT01', field: 'ktsubtype__cisco_sdwan_xe__INT01', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Destination Cisco SD-WAN IOS XE Overlay Session ID', value: 'ktsubtype__cisco_sdwan_xe__INT02', field: 'ktsubtype__cisco_sdwan_xe__INT02', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Application Name', value: 'ktsubtype__cisco_sdwan_xe__STR00', field: 'ktsubtype__cisco_sdwan_xe__STR00', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Application Category', value: 'ktsubtype__cisco_sdwan_xe__STR01', field: 'ktsubtype__cisco_sdwan_xe__STR01', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Application Subcategory', value: 'ktsubtype__cisco_sdwan_xe__STR02', field: 'ktsubtype__cisco_sdwan_xe__STR02', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Application Group', value: 'ktsubtype__cisco_sdwan_xe__STR03', field: 'ktsubtype__cisco_sdwan_xe__STR03', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Application Traffic Class', value: 'ktsubtype__cisco_sdwan_xe__STR04', field: 'ktsubtype__cisco_sdwan_xe__STR04', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Application Business Relevance', value: 'ktsubtype__cisco_sdwan_xe__STR05', field: 'ktsubtype__cisco_sdwan_xe__STR05', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Flow end reason', value: 'ktsubtype__cisco_sdwan_xe__INT00', field: 'ktsubtype__cisco_sdwan_xe__INT00', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE VPN identifier', value: 'ktsubtype__cisco_sdwan_xe__INT64_00', field: 'ktsubtype__cisco_sdwan_xe__INT64_00', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Cisco SD-WAN IOS XE Connection ID', value: 'ktsubtype__cisco_sdwan_xe__INT64_01', field: 'ktsubtype__cisco_sdwan_xe__INT64_01', category: DimensionCategory.CISCO_IOSXE_SDWAN },
  { text: 'Source Silver Peak EdgeConnect From Zone', value: 'ktsubtype__silverpeak__STR02', field: 'ktsubtype__silverpeak__STR02', category: DimensionCategory.SILVERPEAK },
  { text: 'Destination Silver Peak EdgeConnect To Zone', value: 'ktsubtype__silverpeak__STR03', field: 'ktsubtype__silverpeak__STR03', category: DimensionCategory.SILVERPEAK },
  { text: 'Silver Peak EdgeConnect Application Name', value: 'ktsubtype__silverpeak__STR01', field: 'ktsubtype__silverpeak__STR01', category: DimensionCategory.SILVERPEAK },
  { text: 'Silver Peak EdgeConnect Firewall Event', value: 'ktsubtype__silverpeak__INT01', field: 'ktsubtype__silverpeak__INT01', category: DimensionCategory.SILVERPEAK },
  { text: 'Silver Peak EdgeConnect Business Intent Overlay', value: 'ktsubtype__silverpeak__STR00', field: 'ktsubtype__silverpeak__STR00', category: DimensionCategory.SILVERPEAK },
  { text: 'Silver Peak EdgeConnect Application Category', value: 'ktsubtype__silverpeak__STR04', field: 'ktsubtype__silverpeak__STR04', category: DimensionCategory.SILVERPEAK },
  { text: 'Source VXLAN VNI 0 MAC Address', value: 'ktsubtype__vxlan__INT64_00', field: 'ktsubtype__vxlan__INT64_00', category: DimensionCategory.VXLAN },
  { text: 'Source VXLAN VNI 0 IP Address', value: 'ktsubtype__vxlan__INET_00', field: 'ktsubtype__vxlan__INET_00', category: DimensionCategory.VXLAN },
  { text: 'Source VXLAN VNI 0 Port', value: 'ktsubtype__vxlan__INT06', field: 'ktsubtype__vxlan__INT06', category: DimensionCategory.VXLAN },
  { text: 'Source VXLAN VNI 1 MAC Address', value: 'ktsubtype__vxlan__INT64_02', field: 'ktsubtype__vxlan__INT64_02', category: DimensionCategory.VXLAN },
  { text: 'Source VXLAN VNI 1 IP Address', value: 'ktsubtype__vxlan__INET_02', field: 'ktsubtype__vxlan__INET_02', category: DimensionCategory.VXLAN },
  { text: 'Source VXLAN VNI 1 Port', value: 'ktsubtype__vxlan__INT64_07', field: 'ktsubtype__vxlan__INT64_07', category: DimensionCategory.VXLAN },
  { text: 'Destination VXLAN VNI 0 MAC Address', value: 'ktsubtype__vxlan__INT64_01', field: 'ktsubtype__vxlan__INT64_01', category: DimensionCategory.VXLAN },
  { text: 'Destination VXLAN VNI 0 IP Address', value: 'ktsubtype__vxlan__INET_01', field: 'ktsubtype__vxlan__INET_01', category: DimensionCategory.VXLAN },
  { text: 'Destination VXLAN VNI 0 Port', value: 'ktsubtype__vxlan__INT07', field: 'ktsubtype__vxlan__INT07', category: DimensionCategory.VXLAN },
  { text: 'Destination VXLAN VNI 1 MAC Address', value: 'ktsubtype__vxlan__INT64_03', field: 'ktsubtype__vxlan__INT64_03', category: DimensionCategory.VXLAN },
  { text: 'Destination VXLAN VNI 1 IP Address', value: 'ktsubtype__vxlan__INET_03', field: 'ktsubtype__vxlan__INET_03', category: DimensionCategory.VXLAN },
  { text: 'Destination VXLAN VNI 1 Port', value: 'ktsubtype__vxlan__INT64_08', field: 'ktsubtype__vxlan__INT64_08', category: DimensionCategory.VXLAN },
  { text: 'IP TTL', value: 'ktsubtype__vxlan__INT00', field: 'ktsubtype__vxlan__INT00', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 0', value: 'ktsubtype__vxlan__INT01', field: 'ktsubtype__vxlan__INT01', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 0 DSCP', value: 'ktsubtype__vxlan__INT02', field: 'ktsubtype__vxlan__INT02', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 0 TCP Flags', value: 'ktsubtype__vxlan__INT03', field: 'ktsubtype__vxlan__INT03', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 0 Protocol', value: 'ktsubtype__vxlan__INT05', field: 'ktsubtype__vxlan__INT05', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 0 IP TTL', value: 'ktsubtype__vxlan__INT04', field: 'ktsubtype__vxlan__INT04', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 1', value: 'ktsubtype__vxlan__INT08', field: 'ktsubtype__vxlan__INT08', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 1 DSCP', value: 'ktsubtype__vxlan__INT09', field: 'ktsubtype__vxlan__INT09', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 1 TCP Flags', value: 'ktsubtype__vxlan__INT64_04', field: 'ktsubtype__vxlan__INT64_04', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 1 IP TTL', value: 'ktsubtype__vxlan__INT64_05', field: 'ktsubtype__vxlan__INT64_05', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 1 Protocol', value: 'ktsubtype__vxlan__INT64_06', field: 'ktsubtype__vxlan__INT64_06', category: DimensionCategory.VXLAN },
  { text: 'VXLAN VNI 2', value: 'ktsubtype__vxlan__INT64_09', field: 'ktsubtype__vxlan__INT64_09', category: DimensionCategory.VXLAN },
];
